apiVersion: v1
kind: Secret
metadata:
  name: cloudsentinel-secrets
  namespace: cloudsentinel
  labels:
    app.kubernetes.io/name: cloudsentinel
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_YOUR_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_YOUR_SECRET"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/PLACEHOLDER"
  DATABASE_URL: "postgresql://cloudsentinel:password@postgres:5432/cloudsentinel"
